@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMDQsImVtYWlsIjoib0BhLmNvbSIsImZpcnN0bmFtZSI6Im8iLCJsYXN0bmFtZSI6Im8iLCJwc2V1ZG8iOiJKYWNxdW91IGxlIGNyb3F1YW50IiwicGhvbmVfbnVtYmVyIjoiMDE4NDU0NjQxNyIsImF2YXRhciI6Ii9zcmMvY3VzdG9tZXJfcGhvdG9zL2N1c3RvbWVyMTI2LmpwZyIsImlzYWRtaW4iOmZhbHNlLCJjcmVhdGVkX2F0IjoiMjAyMi0wMi0wMVQxMzoxNjowNS42NzNaIiwidXBkYXRlZF9hdCI6IjIwMjItMDItMDFUMTM6MTY6MDUuNjczWiJ9LCJpYXQiOjE2NDM3MjEzNjgsImV4cCI6MTY0MzcyMTY2OH0.zVZW7MLy1PLJ-7cWbpH68_jZTWMPxqHKWIdo6R3q0ZE

###
GET {{host}}/absentees HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/absentees/1 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
POST {{host}}/absentees HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

    {
        "starting_date": "2022-03-10 00:00:00+00",
        "ending_date": "2023-12-08 00:00:00+00",
        "customer_id": 1
    }

###
PATCH {{host}}/absentees/1 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}


    {
        "starting_date": "2022-10-10 00:00:00+00",
        "ending_date": "2023-10-08 00:00:00+00",
        "customer_id": 1
    }
    
###
DELETE {{host}}/absentees/1 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

    {
        "customer_id": 1
    }