@host = http://localhost:5000/api

@access_token = Bearer 

###
GET {{host}}/absences HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/absences/1 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
POST {{host}}/absences HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

    {
        "starting_date": "2022-03-10 00:00:00+00",
        "ending_date": "2023-12-08 00:00:00+00",
        "customer_id": 1
    }

###
PATCH {{host}}/absences/1 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}


    {
        "starting_date": "2022-10-10 00:00:00+00",
        "ending_date": "2023-10-08 00:00:00+00",
        "customer_id": 1
    }
    
###
DELETE {{host}}/absences/1 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

    {
        "customer_id": 1
    }