@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDRvY3NoemwwMDAzaXh1a2tlMmY4dzllIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU1ODI3MjUxLCJleHAiOjE2NTU5MTM2NTF9.2e6w28OSSR1Gz2NNhdeb4VtRBLC1hSzEldzhFgPI2no

@refresh_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDRvY3NoemwwMDAzaXh1a2tlMmY4dzllIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU1ODI3MjUxLCJleHAiOjE2NTg0MTkyNTF9.wbAQasFzJFzVUqJ9cIJhi6RPjSzyeowSZGYcaE9TeHo

###
POST {{host}}/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "firstname": "a",
    "lastname": "a",
    "pseudo": "Jacquou le croquant",
    "phone_number": "0184546417",
    "avatar": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAaCAIAAAAi3QukAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABCSURBVEhLrccxDQAwDMCw8odRdIWxP6c1yY9n9v7oWc961rOe9axnPetZz3rWs571rGc961nPetaznvWsZz3rzd4DxkTAjrVWJ/YAAAAASUVORK5CYII="
}

### Connexion User
POST {{host}}/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "o@o.com",
	"password": "Paradis13$"
}

###
POST {{host}}/auth/refreshToken HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}

###
GET {{host}}/auth/logout HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}