@host = http://localhost:5000/api

@access_token = Bearer 

@refresh_token = Bearer 

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDVjZ3ppaDQwMDAxNnJ1a2RzcXU4dWVnIiwiZW1haWwiOiJ3YXphbXk3NzdAZ21haWwuY29tIiwiaWF0IjoxNjU3Mjg1NDgyLCJleHAiOjE2NTczNzE4ODJ9.wh7Bur1R_EJSVLMutn4U-3oXEPo-o9liHvqAcl-ONrg

###
POST {{host}}/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "titogomez4455@gmail.com",
    "password": "Paradis13$",
    "firstname": "tito",
    "lastname": "gomez",
    "pseudo": "Mirajane",
    "phone_number": "0184546443"
}

###
GET {{host}}/reset HTTP/1.1
content-type: application/json


### Confirm Email
GET {{host}}/auth/confirm?token={{token}} HTTP/1.1
Content-Type: application/json


### Connexion User
POST {{host}}/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "adrien.d@gmail.com",
    "password": "toto"
}

### New mail
GET {{host}}/auth/newmail HTTP/1.1
content-type: application/json



### Connexion User
POST {{host}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

###
POST {{host}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "o@o.com",
	"password": "Paradis13$"
}

###
POST {{host}}/auth/refreshToken HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}

###
GET {{host}}/auth/logout HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}