@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDRwcDkycnkwMDAwemZ1a3VrZHBzajc4IiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU1OTA4NjQ2LCJleHAiOjE2NTU5OTUwNDZ9.OxN428a5jPx99hMHO04n19BYPuvOeTPYGcUtZQp3Xzg

@refresh_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDRwcDkycnkwMDAwemZ1a3VrZHBzajc4IiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU1OTA4NjQ2LCJleHAiOjE2NTg1MDA2NDZ9.gQ0l15RKo04_MzPxD2YfAVS0Hr05nh8cWct_T4FTNu

###
POST {{host}}/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "firstname": "a",
    "lastname": "a",
    "pseudo": "Jacquou le croquant",
    "phone_number": "0184546417",
}

### Connexion User
POST {{host}}/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "o@o.com",
	"password": "Paradis13$"
}

###
POST {{host}}/auth/refreshToken HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}

###
GET {{host}}/auth/logout HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}