@host = http://localhost:5000
@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDRndXNvNHMwMDAwY2p1azRpeHoyenoxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU1NDUwMTE3LCJleHAiOjE2NTU1MzY1MTd9.T7if0r4CUsP6o1oq1dsq7SEPRRlq3OeO4psrYTUZbCM

###
GET {{host}}/api/countries HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/api/countries/cl4gtp6nk0007hfukzvg1fmz0 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}