@host = http://localhost:5000
@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDN5ODlkbWswMDAwMjB1a3VianA5dnBnIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU0MjQ3NTI1LCJleHAiOjE2NTQzMzM5MjV9.DRC8Nt7bJMFGgfaeRnXKM0zEoVhe2FN07UviFN9HZ8Q

###
GET {{host}}/countries HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/countries/cl3y87emq0931bduk6lznccrh HTTP/1.1
content-type: application/json
Authorization: {{access_token}}