@host = http://localhost:5000/api



###
GET {{host}}   HTTP/1.1
Content-Type: application/json

###
GET {{host}}/houses HTTP/1.1
content-type: application/json


###
GET {{host}}/home/full/cl78tbajr19747duk70slfkxr HTTP/1.1
content-type: application/json

###
GET {{host}}/health HTTP/1.1
content-type: application/