@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDQ0M2dpZ3owMDAweW51azRsOHY1bGdmIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU0Njc3NDgxLCJleHAiOjE2NTQ3NjM4ODF9.vVnMqaqTOZBA8cYjA_l-dPxAi__NP2Gvki_E4Gws2r0


###
GET {{host}}/houses HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/houses/full HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/houses/full/cl443b4jn1869t8uk3417sc6u HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/houses/four HTTP/1.1
content-type: application/json
Authorization: {{access_token}}


###
GET {{host}}/houses/cl3x760je00336tukt4ki949f HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
POST {{host}}/houses HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "address": "18 rue du boulet",
    "zipcode": "75010 CEDEX",
    "city": "Montcul",
    "country_id": "cl443b35l0056t8ukxfpfxie2",
    "type_id": "cl443b4fv1785t8uk5pe3gdgc",
    "title": "Maison verte",
    "description": "C'est une maison verte",
    "latitude": "48",
    "longitude": "0.7",
    "map": "https://maps.google.com/maps?q=48,0.7"
}

###
PATCH {{host}}/houses/cl43vym780028ozuk3nptv82a HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

    {
        "rooms": 2,
        "bedrooms": 4,
        "surface": 187,
        "area": 666,
        "floor": 1,
        "internet": true,
        "washing_machine": true,
        "TV": true,
        "microwave": true,
        "dishwasher": true,
        "shower": true,
        "parking": true
    }

###
DELETE {{host}}/houses/cl3x760je00336tukt4ki949f HTTP/1.1
content-type: application/json
Authorization: {{access_token}}