@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDRndXNvNHMwMDAwY2p1azRpeHoyenoxIiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU1MzczNzY0LCJleHAiOjE2NTU0NjAxNjR9.jwu-8G8fnfyed58DJ9W3wM-Bye0qRPiHNcz46Pb29kM


###
GET {{host}}/houses HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/houses/full HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/houses/full/cl4gve8s50004woukkeaxhjor HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/houses/four HTTP/1.1
content-type: application/json
Authorization: {{access_token}}


###
GET {{host}}/houses/cl4gve8s50004woukkeaxhjor HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
POST {{host}}/houses HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "address": "18 rue du boulet",
    "zipcode": "75010 CEDEX",
    "city": "Montcul",
    "country_id": "cl4gtp6oz0056hfuk2of91x7i",
    "type_id": "cl4gtp7z51778hfukn5qstp4r",
    "title": "Maison verte",
    "description": "C'est une maison verte",
    "latitude": "48",
    "longitude": "0.7",
    "map": "https://maps.google.com/maps?q=48,0.7"
}

###
PATCH {{host}}/houses/cl4gve8s50004woukkeaxhjor HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

    {
        "rooms": 2,
        "bedrooms": 4,
        "surface": 190,
        "area": 400,
        "floor": 1,
        "internet": true,
        "washing_machine": true,
        "TV": true,
        "microwave": true,
        "dishwasher": true,
        "shower": true,
        "parking": true
    }

###
DELETE {{host}}/houses/cl4guy49j0035cjuk8z4wyqnb HTTP/1.1
content-type: application/json
Authorization: {{access_token}}