@host = http://localhost:5000/api

@access_token = Bearer 

###
GET {{host}}/matches HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/matches/cl4wk6ykh00254huk6z6rkgml HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
POST {{host}}/matches HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "absence_id": "cl4wk1t3s19909lukqfjd6vif"
}

###
PATCH {{host}}/matches/cl4wk6ykh00254huk6z6rkgml HTTP/1.1
content-type: application/json
Authorization: {{access_token}}


{
}
    
###
DELETE {{host}}/matches/1 HTTP/1.1
content-type: application/json
Authorization: {{access_token}}