@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDQzdnZtZXMwMDAwb3p1a252dmt1MHR6IiwiZW1haWwiOiJhQGEuY29tIiwiaWF0IjoxNjU0NTg5NTI1LCJleHAiOjE2NTQ2NzU5MjV9.8HFx9RssO-VpjhjHG0rw_kBe2Pz6ixjWcUcT9fCyG8A


###
GET {{host}}/photos HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

### GetPhotoById
GET {{host}}/photos/cl43w1kl80058ozuk4ykyoees HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

### GetPhotoByHouseId
GET {{host}}/photos/house/cl43vym780028ozuk3nptv82a HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
POST {{host}}/photos/ HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "photo": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAaCAIAAAAi3QukAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABCSURBVEhLrccxDQAwDMCw8odRdIWxP6c1yY9n9v7oWc961rOe9axnPetZz3rWs571rGc961nPetaznvWsZz3rzd4DxkTAjrVWJ/YAAAAASUVORK5CYII=",
    "house_id": "cl43vym780028ozuk3nptv82a"
}
    
###
PATCH {{host}}/photos/cl43w1kl80058ozuk4ykyoees HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "photo":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfqzqzAAAaCAIAAAAi3QukAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAAtSURBVEhLY+xgEGWgBmCC0hSDUYMIg1GDCINRgwiDUYMIg1GDCINRgwgBBgYAU7QA0Su7uLMAAAAASUVORK5CYIfe"
}
    
###
DELETE {{host}}/photos/cl3z17u3m0009miuk1n4dihdf HTTP/1.1
content-type: application/json
Authorization: {{access_token}}