@host = http://localhost:5000/api

@access_token = Bearer 

###
GET {{host}}/types/ HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

###
GET {{host}}/types/cl3y87f5g1799bdukjxt2ntmi HTTP/1.1
content-type: application/json
Authorization: {{access_token}}